name=input("Enter the name:")
feel=input("LOVE or HATE:")
feel1=input("DITCH or HURT:")
celebrity=input("SAM OR RON:")
print("Hello " + name )
print("DO  you know how much i " +feel + " you?")
print("Please do not "+ feel1 + " me!")
print("I love " + celebrity)
